import Haki

print ("Masukan Judul : ")
title=input()
print ("Masukan deskripsi : ")
decription=input()
print ("Masukan tanggal Dibuat : (format 2020-01-12)")
date=input()
print ("Masukan Nama : ")
name=input()
print("Masukan Alamat : ")
address=input()
print("Masukan Kota : ")
city=input()
print("Masukan Kode Pos :  (Wajib Angka !!!) ")
zip_code=input()
print("Masukan Provinsi : (Wajib Huruf Kecil !!!)")
province=input()
jalan=Haki.EHaki(title, decription, date, name, address, city, zip_code, province)
jalan.web()
jalan.permohonan_baru()
jalan.data_pencipta()
jalan.pemegang_hak_cipta()
jalan.lampiran()